services:
  - type: web
    name: trainup-api
    env: docker
    plan: free
    region: oregon
    docker:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: "sql212.infinityfree.com"
      - key: DB_USER
        value: "if0_40180454"
      - key: DB_PASSWORD
        value: "DFFVnI7Dza5MA"
      - key: DB_NAME
        value: "if0_40180454_train_up"
