services:
  - type: web
    name: trainup-api
    env: docker
    plan: free
    region: oregon
    docker:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: "fdb1034.awardspace.net"
      - key: DB_USER
        value: "4701937_trainup"
      - key: DB_PASSWORD
        value: "gONECHIPO12*"  # Replace with your actual password
      - key: DB_NAME
        value: "4701937_trainup"
