services:
  - type: web
    name: trainup-api
    env: docker
    plan: free
    region: oregon
    docker:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: "sql8.freesqldatabase.com"
      - key: DB_USER
        value: "sql8805800"
      - key: DB_PASSWORD
        value: "WpKfZ6vfYc"  # Replace with your actual password
      - key: DB_NAME
        value: "sql8805800"
